name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  unit-test:
    name: 1. Unit Test (pytest)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pip install pytest httpx

      - run: PYTHONPATH=. pytest


  sast:
    name: 2. SAST (Bandit)
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install bandit
      - run: bandit -r . -ll


  sca:
    name: 3. SCA (pip-audit)
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pip install pip-audit

      - run: pip-audit -r requirements.txt


  secret-scan:
    name: 4. Secret Scan (Gitleaks)
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --verbose --redact


  docker-build-push:
    name: 5. Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [sast, sca, secret-scan]

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build -t yourdockerhubusername/devsecops-app:latest .

      - name: Push Image
        run: |
          docker push yourdockerhubusername/devsecops-app:latest


  image-scan:
    name: 6. Image Scan (Trivy)
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Scan Docker Image from Docker Hub
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: hildan001/devsecops-app
          format: table
          exit-code: 1
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
