name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
      - sesi30-devsecops
  pull_request:

jobs:

  # 1️⃣ UNIT TEST
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pip install pytest
      - run: PYTHONPATH=. pytest


  # 2️⃣ SAST (Bandit)
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install bandit
      - run: bandit -r app


  # 3️⃣ SCA (pip-audit)
  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install pip-audit
      - run: pip-audit -r requirements.txt


  # 4️⃣ SECRET SCAN (Gitleaks)
  secret_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2


  # 5️⃣ BUILD & PUSH DOCKER IMAGE
  build_and_push:
    runs-on: ubuntu-latest
    needs: [unit_test, sast, sca, secret_scan]

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notes-app:latest .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notes-app:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notes-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notes-app:${{ github.sha }}


  # 6️⃣ IMAGE SCAN (Trivy)
  image_scan:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/notes-app:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
